POST http://localhost:3000/ticket-counter/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbDFAZ21haWwuY29tIiwiaWQiOjMsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjU0MDIwNTIsImV4cCI6MTY2NTQwNTY1Mn0.q6aiFmIQa0mjfyoSuNG_wJu9zj00fsMEdQJ5QovAOVE

{
    "seatNo":"we",
    "flightId":"4ccaf2a0-82f5-406e-9993-643d9e8a567b"
}



### Get all ticket
GET http://localhost:3000/ticket-counter/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY1NDAxNjQ3LCJleHAiOjE2NjU0MDUyNDd9.9CFSFPzH0NaguDsrNn1bTn3E2kSjQZJKlIJ7awU54fI



### Cancel the ticket
DELETE http://localhost:3000/ticket-counter/23323
content-type: application/json