POST http://localhost:3000/planes
Content-Type: application/json

{
    "name": "saja yatayat",
    "airlineId" : "04d705cf-cf5b-458d-b434-553a3727709f",
    "totalSeats": 68
}


### Get all planes
GET http://localhost:3000/planes/
content-type: application/json



### Get all planes by airlineId
GET http://localhost:3000/planes?airlineId=
content-type: application/json



### Get plane by planeId
GET http://localhost:3000/planes/a86598c-dab9-816d-df8ae2f1d9fe
content-type: application/json


### update planes
PATCH http://localhost:3000/planes/1
content-type: application/json

{
    "name": "American airlines"
}