POST http://localhost:3000/planes
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjQyMDc1NTIsImV4cCI6MTY2NDIxMTE1Mn0.vE9lA8xv2MZe6ajEequhkQr5--YV9uW3CkCbYV5wylU

{
    "name": "Xpress 342",
    "airlineId" : "34bbca8e-0b99-469e-8a95-b16b02df108a",
    "seats": [
        {
            "seatNo": "A34",
            "type": "business"
        },
        {
            "seatNo": "A04",
            "type": "economy"
        }
    ]
    
}


### Get all planes
GET http://localhost:3000/planes/
content-type: application/json



### Get all planes by airlineId
GET http://localhost:3000/planes?airlineId=
content-type: application/json



### Get plane by planeId
GET http://localhost:3000/planes/11daf697-a483-48b6-8742-31490b96ba38
content-type: application/json


### update planes
PATCH http://localhost:3000/planes/1
content-type: application/json

{
    "name": "American airlines"
}