POST http://localhost:3000/planes
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjM2MjNlNThmNmY1NzkyNGQ3MGViYTkxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3NDYyNzAxLCJleHAiOjE2Njc0NjYzMDF9.n0heXpwqADqG89wu47kAx5KWwjYWWqEMMIbMpxBG4TM

{
    "name": "endpress 342",
    "airlineId" : "63623ef9c1690af184b8ff01",
    "seats": [
        {
            "seatNo": "A34",
            "type": "business"
        },
        {
            "seatNo": "A04",
            "type": "economy"
        }
    ]
    
}


### Get all planes
GET http://localhost:3000/planes/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjM2MjNlNThmNmY1NzkyNGQ3MGViYTkxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3NDYyNzAxLCJleHAiOjE2Njc0NjYzMDF9.n0heXpwqADqG89wu47kAx5KWwjYWWqEMMIbMpxBG4TM



### Get all planes by airlineId
GET http://localhost:3000/planes?airlineId=63623ef9c1690af184b8ff01
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjM2MjNlNThmNmY1NzkyNGQ3MGViYTkxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3NDYyNzAxLCJleHAiOjE2Njc0NjYzMDF9.n0heXpwqADqG89wu47kAx5KWwjYWWqEMMIbMpxBG4TM



### Get plane by planeId
GET http://localhost:3000/planes/63637917bb03b56ebfeeafa9
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjM2MjNlNThmNmY1NzkyNGQ3MGViYTkxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3NDYyNzAxLCJleHAiOjE2Njc0NjYzMDF9.n0heXpwqADqG89wu47kAx5KWwjYWWqEMMIbMpxBG4TM


### update planes
PATCH http://localhost:3000/planes/1
content-type: application/json

{
    "name": "American airlines"
}