POST http://localhost:3000/airlines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBleGFtcGxlLmNvbSIsImlkIjozLCJyb2xlIjoibm9ybWFsIiwiaWF0IjoxNjYyNjI3MzQwLCJleHAiOjE2NjI2MzA5NDB9.57gFVyLS3jkKQz-FxsS_vAoVtbctOrA6ToCCoGNyCqg

{
    "name": "Korean Airlines",
    "totalAirplanes": 7
}


### Get all airlines
GET http://localhost:3000/airlines/
content-type: application/json


### update airlines
PATCH http://localhost:3000/airlines/1
content-type: application/json

{
    "name": "American airlines"
}