POST  http://localhost:3000/flights
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjM1MDc0OTQsImV4cCI6MTY2MzUxMTA5NH0.nnql_PDIs8nzwl-Zts7e1Pf_d2-N_zIfAaldebzNuvI

{
    "date":666661,
    "planeId" : "b842a457-c705-4839-808f-23a81a6cd292"
}


### Get all available flights
Get http://localhost:3000/flights
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjM1MDc0OTQsImV4cCI6MTY2MzUxMTA5NH0.nnql_PDIs8nzwl-Zts7e1Pf_d2-N_zIfAaldebzNuvI


### Update flight status
Patch http://localhost:3000/flights
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6Miwicm9sZSI6Im5vcm1hbCIsImlhdCI6MTY2MzUwNzk3MCwiZXhwIjoxNjYzNTExNTcwfQ.0xyb2vK2ci8V_danAgV7Qqr57rDNPt1T-urp57HvdpY

{
    "status": "inAir"
}
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6Miwicm9sZSI6Im5vcm1hbCIsImlhdCI6MTY2MzUwNzk3MCwiZXhwIjoxNjYzNTExNTcwfQ.0xyb2vK2ci8V_danAgV7Qqr57rDNPt1T-urp57HvdpY