POST  http://localhost:3000/flights
content-type: application/json

{
    "date":666661,
    "planeId" : "c6b149a8-352c-4f5d-9e46-5aedf4229228"
}


### Get all available flights
Get http://localhost:3000/flights
content-type: application/json