POST  http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "mongodb@gmail.com",
    "password": "test@123",
    "userType":"normal"
}


### SIgn in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "mongodb@gmail.com",
    "password": "test@123"
}